### ISSUE TITLE
Failing to properly write file extension in music.yaml causes strange behavior.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/tsuserver3#111] opened 2020-08-07 12:58 UTC
Instead of erroring or warning you in some helpful manner, if you manage to make a music.yaml which doesn't have file extensions at hte end of one or more songs you get this behavior from the jukebox, where area list + music are all on the same page:
[https://i.imgur.com/6jWJWGl.png](https://i.imgur.com/6jWJWGl.png)

**Comment by Iamgoofball** [comment] 2020-08-07 20:12
This is due to a regression. In 2.7 for AOV I made music not care about the file type on the serverside, with the client simply looking for any mp3/opus/wav/ogg/whatever with the same name. This somehow got lost in the merge, and will need to be re-added before a full launch can continue.

**Comment by caleb-mabry** [comment] 2021-01-26 02:39
Without providing a whole ton of validation on the server side (which should probably be done). Before this issue is fixed in the client, we can add a basic check to see if there is a period in the filename signifying a file.extension?

**Comment by caleb-mabry** [comment] 2021-01-29 03:10
@oldmud0 
Can we close this issue?

**Comment by oldmud0** [comment] 2021-01-30 19:41
Sure

**Closed as completed by oldmud0** 2021-01-30 19:41 UTC
